// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewAnimal struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ClassID     string  `json:"classId"`
}

type NewClass struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}
